routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CompanieController;
use App\Http\Controllers\Admin\PrealertsController;
use App\Http\Controllers\Admin\PackagesController;
use App\Http\Controllers\Admin\InstrucctionController;
use App\Http\Controllers\Admin\ShippingsController;
use App\Http\Controllers\Admin\ShippingsInvoicesController;
use App\Http\Controllers\Admin\InvoiceController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\Admin\RateShippingsController;
use App\Http\Controllers\Admin\BoxController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\StatusController;
use App\Http\Controllers\Clients\PrealertsClientController;
use App\Http\Controllers\Clients\PackagesClientController;
use App\Http\Controllers\Clients\InstrucctionClientController;
use App\Http\Controllers\Clients\ShippingsClientController;
use App\Http\Controllers\Clients\InvoiceClientController;

App::setLocale('es');

Route::get('/', [HomeController::class, 'index']
);

Auth::routes();

/*get de estados, ciudades y map*/
Route::get('users/iframeMap', [RegisterController::class, 'iframeMap']
)->name('users.iframeMap');
Route::get('/findCities/{state_id}', [RegisterController::class, 'findCities'])->name('users.findCities');
Route::get('/users/iframeMapFind/{log}/{lat}', [RegisterController::class, 'iframeMapFind'])->name('users.iframeMapFind');
Route::get('/users/registerSuccess', [RegisterController::class, 'registerSuccess'])->name('users.register_success');


Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');

Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password'); 
Route::get('email-success', [ForgotPasswordController::class, 'submitEmailSuccess'])->name('forget.email_success'); 
Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/redirects', [HomeController::class, 'index'])->name('redirects');

//rutas accesibles solo para clientes
Route::group(['middleware' => ['role:cliente'], 'prefix' => 'cliente'], function () {


	Route::get('/ajax-autocomplete-search', [InstrucctionClientController::class, 'selectSearch'])->name('clients.users.usersAutocomplete');
	
   //prealerts
	Route::get('/prealerts/filters', [PrealertsClientController::class, 'getFilterPrealerts'])->name('clients.prealerts.getFilterPrealerts');
	Route::get('/prealerts/companies', [PrealertsClientController::class, 'getCompanies'])->name('prealerts.getCompanies');
	Route::get('/prealerts/companiesq', [PrealertsClientController::class, 'getCompaniesQuery'])->name('prealerts.getCompaniesQuery');
	Route::post('/prealerts/storeCompany', [PrealertsClientController::class, 'storeCompany'])->name('clients.prealerts.storeCompany');

	
	Route::resource('prealerts', 'Clients\PrealertsClientController')
	->names([
		    'index' => 'clients.prealerts.index',
		    'create'=> 'clients.prealerts.create',
		    'store' => 'clients.prealerts.store',
		    'edit' => 'clients.prealerts.edit',
		    'update' => 'clients.prealerts.update',
		    'destroy' => 'clients.prealerts.destroy'
		]);

	

	Route::delete('/prealerts/delete/{id}', [PrealertsClientController::class, 'destroy'])->name('clients.prealerts.delete');
	

	//Package
	Route::get('/iframeMap', [PackagesClientController::class, 'iframeMap']
		)->name('packages.iframeMap');
	Route::get('/packages/iframeMapFind/{log}/{lat}', [PackagesClientController::class, 'iframeMapFind'])->name('packages.iframeMapFind');
	Route::get('/packages/filters', [PackagesClientController::class, 'getFilterPackages'])->name('clients.packages.getFilterPackages');
	Route::post('/packages/confirmed', [PackagesClientController::class, 'confirmed'])->name('clients.packages.confirmed');
	Route::get('/packages/receipt/{id}', [PackagesClientController::class, 'receipt'])->name('clients.packages.receipt');
	Route::get('/packages/view/{id}', [PackagesClientController::class, 'view'])->name('clients.packages.view');
	Route::get('/packages/assing/{id}', [PackagesClientController::class, 'assing'])->name('clients.packages.assign');

	Route::resource('packages', 'Clients\PackagesClientController')->names([
		    'index' => 'clients.packages.index',
		    'create'=> 'clients.packages.create',
		    'store' => 'clients.packages.store',
		    'edit' => 'clients.packages.edit',
		    'update' => 'clients.packages.update',
		    'destroy' => 'clients.packages.destroy'
		]);

	//Instrucctions
	Route::get('/instrucctions/filters', [InstrucctionClientController::class, 'getFilterPackages'])->name('clients.instrucctions.getFilterPackages');
	Route::get('/instrucctions/receipt/{id}', [InstrucctionClientController::class, 'receipt'])->name('clients.instrucctions.receipt');
	Route::get('/instrucctions/view/{id}', [InstrucctionClientController::class, 'view'])->name('clients.instrucctions.view');
	Route::get('/instrucctions/assing/{id}', [InstrucctionClientController::class, 'assing'])->name('clients.instrucctions.assign');
	Route::get('/instrucctions/iframeMapFind/{log}/{lat}', [InstrucctionClientController::class, 'iframeMapFind'])->name('instrucctions.iframeMapFind');
	Route::resource('instrucctions', 'Clients\InstrucctionClientController')->names([
		    'index'   => 'clients.instrucctions.index',
		    'create'  => 'clients.instrucctions.create',
		    'store'   => 'clients.instrucctions.store',
		    'edit'    => 'clients.instrucctions.edit',
		    'update'  => 'clients.instrucctions.update',
		    'destroy' => 'clients.instrucctions.destroy'
		]);

	//Shippings 
	Route::get('/iframeMap/shippings', [ShippingsClientController::class, 'iframeMap']
		)->name('shippings.iframeMap');
	Route::get('/iframeMapFind/shippings/{log}/{lat}', [ShippingsClientController::class, 'iframeMapFind'])->name('shippings.iframeMapFind');
	Route::get('/shippings/filters', [ShippingsClientController::class, 'getFilterShippings'])->name('clients.shippins.getFilterShippings');
	Route::get('/shippings/assing/{id}', [ShippingsClientController::class, 'assing'])->name('clients.shippings.assign');
	Route::post('/shippings/add', [ShippingsClientController::class, 'addShipping'])->name('clients.shippings.addShipping');
	Route::get('/shippings/receipt/{id}', [ShippingsClientController::class, 'receipt'])->name('clients.shippings.receipt');
	Route::get('/printInvoice/{id}', [ShippingsClientController::class, 'printInvoice'])->name('clients.shippings.printInvoice');


	Route::resource('shippings', 'Clients\ShippingsClientController')->names([
		    'index'   => 'clients.shippings.index',
		    'show' 	  => 'clients.shippings.show',
		    'create'  => 'clients.shippings.create',
		    'store'   => 'clients.shippings.store',
		    'edit'    => 'clients.shippings.edit',
		    'update'  => 'clients.shippings.update',
		    'destroy' => 'clients.shippings.destroy',

		]);
	
	Route::post('/calculatorClient', [PackagesClientController::class, 'calculatorClient'])->name('calculatorClient');

	//Invoices
	Route::get('/invoices/filters', [InvoiceClientController::class, 'getFilterInvoices'])->name('clients.invoices.getFilterInvoices');

	Route::get('/printInvoice/invoices/{id}', [InvoiceClientController::class, 'printInvoice'])->name('clients.invoices.printInvoice');

	Route::get('/printInvoice/invoices/paid/{id}', [InvoiceClientController::class, 'printInvoicePaid'])->name('clients.invoices.printInvoice.paid');

	Route::get('/payment/{id}', [InvoiceClientController::class, 'paymentInvoice'])->name('clients.invoices.payment');

	Route::get('/transfer/{id}', [InvoiceClientController::class, 'paymentTransfer'])->name('clients.invoices.paymentTransfer');

	Route::post('transferStore', [InvoiceClientController::class, 'transferStore'])->name('clients.invoices.transferStore');

	Route::resource('invoices', 'Clients\InvoiceClientController')->names([
		    'index'   => 'clients.invoices.index',
		    'create'  => 'clients.invoices.create',
		    'store'   => 'clients.invoices.store',
		    'edit'    => 'clients.invoices.edit',
		    'update'  => 'clients.invoices.update',
		    'destroy' => 'clients.invoices.destroy'
		]);
});


//rutas accesibles solo para admin
Route::group(['middleware' => ['role:admin'], 'prefix' => 'admin'], function () {

	//Generales
	Route::get('/iframeMap', [UserController::class, 'iframeMap']
		)->name('iframeMap');
	Route::get('/findCities/{state_id}', [UserController::class, 'findCities'])->name('users.findCities');
	Route::get('/users/iframeMapFind/{log}/{lat}', [UserController::class, 'iframeMapFind'])->name('users.iframeMapFind');
	Route::get('/countNotifications', [UserController::class, 'countNotifications']
		)->name('admin.countNotifications');

	Route::get('/ajax-autocomplete-search', [UserController::class, 'selectSearch'])->name('users.usersAutocomplete');
	//users
	Route::get('/users/filters', [UserController::class, 'getFilterUsers'])->name('users.getFilterUsers');
	Route::post('/users/code', [UserController::class, 'codeUpdate'])->name('users.codeUpdate');
	Route::get('/users/edit/{id}', [UserController::class, 'edit'])->name('users.edit');

	Route::resource('users', 'Admin\UserController')->names([
	    'index'   => 'admin.users.index',
	    'create'  => 'admin.users.create',
	    'store'   => 'admin.users.store',
	    'edit'    => 'admin.users.edit',
	    'update'  => 'admin.users.update',
	    'destroy' => 'admin.users.destroy',

	]);

app/Models/Instrucctions.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Instrucctions extends Model
{
    protected $table = 'instrucctions';
    public $timestamps = false;

}

resources/views/admin/instrucctions/map.blade.php
<!DOCTYPE html>
<html>

  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=7, IE=9, IE=10">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1,user-scalable=no"/>
    <title>Simple Map</title>
    

    <style>
      html, body, #map {
        height: 100%;
        width: 100%;
        margin: 0;
        padding: 0;
      }
      body {
        background-color: #FFF;
        overflow: hidden;
        font-family: "Trebuchet MS";
      }
    </style>

    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCWV62-MOsXA-ifSUGAb5HXtyikHDVtuJU&callback=myMap"
      async
    ></script>
    <script type="text/javascript">
      function myMap() {

        _lat = parseFloat("<?=$lati?>")
        _lon = parseFloat("<?=$long?>")

        var map = new google.maps.Map(document.getElementById("map"), {
          center:new google.maps.LatLng( _lat,_lon),
          zoom: 8,
          scrollwheel: true,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        });


        
        var marker = new google.maps.Marker({
          map: map,
          position:  {lat:_lat , lng: _lon},
        });
      }


    </script>
  </head>

  <body>

    <div id="map"></div>
  </body>
</html>

          

resources/views/admin/instrucctions/view.blade.php
@extends('adminlte::page')
@section('title', 'INSTRUCCIONES')

@section('content_header')
    <h4><b style="color:#24298D; font-weight: 900;">DETALLE DE INSTRUCCIÓN</b></h4>
@stop

@section('content')


@if (\session('errors'))
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
@endif
@if (session()->has('success'))
    <div class="alert alert-success">
       <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>{!! session()->get('success')!!}
            <li>  </li>
        </ul>
    </div>
@endif
<div class="alert alert-success alert2" style="display: none">
   <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <span id="msg"></span>
</div>

  <section class="content">
      <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                   <div class="card">
                      <!-- /.card-header -->
                      <div class="card-body">
                      
                          <div class="row">
                             <div class="row col-8">
                              <div class="col-6">
                                <label class="text-primary" style="color:#24298D !important; font-size:15px !important; letter-spacing: -0.5px !important;">DATOS BÁSICOS</label>
                                
                                  <hr>
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">WAREHOUSE: </label><span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{  $package->ware_house }}</span><br>
                                  
                                  
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">TRACKING: </label><span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{  $package->trackings[0]->tracking }}</span><br>
                                  
                                  
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">CÓDIGO DE CLIENTE: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{ $package->user->code }}
                                      </span><br>
                                  
                                  
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">NOMBRE DE CLIENTE: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{ $package->user->name.' '.$package->user->last_name }}
                                      </span><br>
                                  
                                 
                                  
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">CONTENIDO: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{ $package->description }}
                                      </span><br>
                                  
                                
                              </div>
                                
  
                              <div class="col-6">
                                <label class="text-primary" style="color:#24298D !important; font-size:15px !important; letter-spacing: -0.5px !important;">MEDIDAS</label>
                                <hr>
                               
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">ANCHO: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{ $package->width }} IN
                                      </span><br>
                                  
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">ALTO: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{ $package->high }} IN
                                      </span><br>
                                  
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">LARGO: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{ $package->long }} IN
                                      </span><br>
                                 
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">PESO: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{ $package->weight }} LB
                                      </span><br>
                                  
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">NÚMERO DE PIEZAS: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{ $package->nro_pieces }}
                                      </span><br>
                                  
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">LB VOLUMÉTRICA: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{  number_format((($package->long * $package->width * $package->high)/ 166) * $package->nro_pieces, 3) }}
                                      </span><br>
                                  
                                      <label style="font-size:15px !important; letter-spacing: -0.5px !important;">PIE CÚBICO: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{  number_format((($package->long * $package->width * $package->high)/ 1728) * $package->nro_pieces, 3) }}
                                      </span><br>
                                 
                              </div>

                              <div class="col-12">
                                <label class="text-primary" style="color:#24298D !important; font-size:15px !important; letter-spacing: -0.5px !important;">INSTRUCCIONES</label>
                                 <hr>
                                        <label style="font-size:15px !important; letter-spacing: -0.5px !important;">ALMACÉN: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{ $package->hold==1? 'Guardar en Almacen': 'No Guardar en Almacen' }} 
                                        </span>
                                        <br>
                                        <label style="font-size:15px !important; letter-spacing: -0.5px !important;">SEGURO: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">${{ $package->insured }} 
                                        </span>
                                   <br>
                                        <label style="font-size:15px !important; letter-spacing: -0.5px !important;">REEMPAQUE: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{ $package->repackage == 1? 'Con reempaque': 'Sin reempaque' }} 
                                        </span>
                                   <br>
                                   
                                        <label style="font-size:15px !important; letter-spacing: -0.5px !important;">TIPO DE ENVÍO: </label> <span class="pl-2" style="font-size:15px !important; letter-spacing: -0.5px !important;">{{ $package->shippins_id == 1? 'MARÍTIMO': 'AÉREO' }} 
                                        </span>
                                    
                              </div>
                            </div>
                              
                            <div class="col-4">
                              <div class="col-12">
                                <label class="text-primary" style="color:#24298D !important; font-size:15px !important; letter-spacing: -0.5px !important;">LISTADO DE TRACKING</label>
                                  <div class="row card mb-2 border rounded-lg  bg-light" style="max-height: 170px !important; min-height: 160px !important; font-size: 15px">

                                    <div class="card-body pt-2" style="display: block;">
                                        <ul id="list_tracking" class="nav nav-pills flex-column">

                                          @foreach($package->trackings as $item)
                                           <li class="nav-item ">
                                             <b class="pl-3">{{ $item->tracking }}</b>
                                          </li>
                                          @endforeach
                                        </ul>
                                    </div>
                                </div>
                              </div>

                              <label class="pt-2 text-primary" style="color:#24298D !important; font-size:15px !important; letter-spacing: -0.5px !important;">IMAGEN DEL PAQUETE</label>
                              <div class="col-12 border rounded-lg text-center p-3" style="max-height: 185px !important; max-width: auto !important;">
                                  <img src="{{ $package->images[0]->url }}" class="img-fluid" id="img-upload" style="max-height: 150px !important; max-width: auto  !important;"/>
                              </div>
                            </div>
                          
                          </div>

                    {{-- Save button --}}
                    <div class="row mb-3 mt-1 float-right ">
                      <div class="col-12">
                        <a href="{{ route('admin.instrucctions.index') }}" class="btn btn-default" id="btn_cancel" value="cancel">VOLVER
                        </a>
                      </div>
                    </div>

                </form>

              </div>
            </div>

          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
  </section>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('js/plugins/jquery-confirm/dist/jquery-confirm.min.css') }}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500;600;700;800;900&display=swap' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="{{ asset('favicon.ico') }}">
</head>
@stop

@section('js')

<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('js/plugins/jquery-confirm/dist/jquery-confirm.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script src="{{ asset('js/plugins/input-number/input-number-format.jquery.min.js') }}"></script>
</head>

<script type="text/javascript">
$(document).ready(function() {


});
 
</script>
@stop
<style type="text/css">
body{
        font-family: 'Montserrat', sans-serif !important;
        
        text-transform: uppercase !important;
    }
</style>